version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/BangKok
      PGTZ: Asia/BangKok
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - document-management-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  keycloak:
    image: atearlgrey/plant-growth-identity:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=192.168.103.136
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-init/realm/:/opt/keycloak/data/import/
    networks:
      - document-management-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  document-app:
    image: atearlgrey/document-management-app-demo:latest
    environment:
      - PRODUCTION=true
      - ENVIRONMENT=production
      - ENABLE_AUTH=true
      - AUTHORITY_URL=http://192.168.103.136:8080
      - AUTHORITY_REALM=plant-growth
      - AUTHORITY_CLIENT_ID=plant-growth-client
      - SERVICE_URL=http://192.168.103.136:4301
    ports:
      - "80:80"
      - "443:443"
    networks:
      - document-management-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
volumes:
  postgres_data:

networks:
  document-management-net:
    name: document-management-net
    driver: overlay
    attachable: true
